"use client";

import { motion } from "framer-motion";
import { Brain, Lightbulb, Users } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";

interface CollectiveInsightProps {
  userLevel?: number;
}

/**
 * AI-mediated Collective Insight
 * 
 * A quiet social layer that creates a sense of belonging
 * to a professional community WITHOUT social feed mechanics.
 * 
 * This is NOT a social network.
 * This is collective reasoning insight, mediated by AI.
 * 
 * Rules:
 * - No usernames
 * - No avatars
 * - No likes
 * - No comments
 * - No timestamps
 * - Read-only
 * - 2-4 bullet insights max
 * 
 * UX Intention:
 * User should feel: "I am not alone. Others think seriously about cooking like I do."
 * NOT: "I need to perform for others."
 */
export function CollectiveInsight({ userLevel = 1 }: CollectiveInsightProps) {
  const { t } = useLanguage();

  // Static placeholder insights for MVP
  // Future: Generated by backend AI aggregation based on user level, recent actions, learning path
  const insights = t?.profile?.collectiveInsight?.insights || [
    "Wielu użytkowników na poziomie 1 skupia się teraz bardziej na zarządzaniu lodówką niż na nowych przepisach.",
    "Często pojawia się potrzeba uproszczenia technik zamiast ich komplikowania.",
    "To dobry moment, aby zacząć kontrolować koszt bez utraty smaku.",
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.2 }}
      className="bg-gradient-to-br from-slate-50 to-gray-100 dark:from-gray-800/50 dark:to-gray-900/50 rounded-2xl border border-slate-200 dark:border-gray-700 p-6 shadow-sm"
    >
      {/* Header */}
      <div className="flex items-start gap-3 mb-4">
        <div className="p-2 bg-gradient-to-br from-purple-500/10 to-blue-500/10 rounded-lg">
          <Brain className="w-6 h-6 text-purple-600 dark:text-purple-400" />
        </div>
        <div className="flex-1">
          <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-1">
            {t?.profile?.collectiveInsight?.title || "🧠 Jak myślą inni kucharze na Twoim etapie"}
          </h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">
            {t?.profile?.collectiveInsight?.subtitle || "Anonimowe obserwacje oparte na decyzjach innych użytkowników"}
          </p>
        </div>
      </div>

      {/* Insights List */}
      <div className="space-y-3">
        {insights.map((insight: string, index: number) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.3, delay: 0.3 + index * 0.1 }}
            className="flex items-start gap-3 group"
          >
            <div className="mt-1 p-1.5 bg-gradient-to-br from-blue-500/10 to-cyan-500/10 rounded-md group-hover:from-blue-500/20 group-hover:to-cyan-500/20 transition-colors">
              <Lightbulb className="w-4 h-4 text-blue-600 dark:text-blue-400" />
            </div>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed flex-1">
              {insight}
            </p>
          </motion.div>
        ))}
      </div>

      {/* Footer Note */}
      <div className="mt-4 pt-4 border-t border-slate-200 dark:border-gray-700">
        <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
          <Users className="w-3.5 h-3.5" />
          <span>
            {t?.profile?.collectiveInsight?.footer || "Agregowane anonimowo z działań społeczności"}
          </span>
        </div>
      </div>
    </motion.div>
  );
}
